import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Navbar from '../components/navbar/Navbar';
import Hero from '../components/Hero/Hero';
import data from '../data/slidesData'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Hero
        slides={data}
      />
    </div>
  )
}
