import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Navbar from '../components/navbar/Navbar';
import Hero from '../components/Hero/Hero';
import HeroData from '../data/slidesData';
import WhyUs from '../components/WhyUs/WhyUs';
import WhyUsLogoData from '../data/whyUsLogosData';
import WhyUsPros from '../components/WhyUs/WhyUsPros';
import WhyUsProsSection from '../data/WhyUsProsSection';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Hero slides={HeroData} />
            <WhyUs logos={WhyUsLogoData} prosSection={WhyUsProsSection} />
            <WhyUsPros prosSection={WhyUsProsSection} />
        </div>
    );
}
